# syntax=thxcode/gguf-packer:latest

ARG        MODEL_NAME=Qwen2-0.5B-Instruct
ARG        CONVERT_TYPE=F16
ARG        QUANTIZE_TYPE=Q5_K_M

FROM       scratch AS f16
LABEL      gguf.model.from="HuggingFace"
LABEL      gguf.model.usage="text"
CONVERT    --from=context --type=${CONVERT_TYPE} /model ${MODEL_NAME}.${CONVERT_TYPE}.gguf
CMD        ["-m", "${MODEL_NAME}.${CONVERT_TYPE}.gguf", "-c", "8192", "-np", "4"]

FROM       scratch
LABEL      gguf.model.from="HuggingFace"
LABEL      gguf.model.usage="text"
QUANTIZE   --from=f16 --type=${QUANTIZE_TYPE} ${MODEL_NAME}.${CONVERT_TYPE}.gguf ${MODEL_NAME}.${QUANTIZE_TYPE}.gguf
CMD        ["-m", "${MODEL_NAME}.${QUANTIZE_TYPE}.gguf", "-c", "8192", "-np", "4"]
