name: clean

permissions:
  contents: write
  pull-requests: read
  actions: write

defaults:
  run:
    shell: bash

on:
  workflow_dispatch: { }
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC

jobs:
  clean:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - name: Remove Cache
        uses: actions/github-script@v7
        with:
          # clean up caches,
          # ref to https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries,
          # and https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache.
          script: |
            const owner = context.repo.owner
            const repo = context.repo.repo
            var deleteCaches = new Array()
            
            // get candidate items.
            const { data: cs } = await github.rest.actions.getActionsCacheList({
              owner: owner,
              repo: repo,
            });
            for (const c of cs.actions_caches) {
              // clean closed pull request caches.
              if (c.ref.match(/^refs\/pull\/.*$/)) {
                var prNum = c.ref.replace(/[^\d]/g, "")
                const { data: pr } = await github.rest.pulls.get({
                  owner: owner,
                  repo: repo,
                  pull_number: prNum,
                })
                if (pr.state === 'closed') {
                  deleteCaches.push(c)
                }
                continue
              }
              ${{ github.event_name == 'schedule' && '' || '// clean main branch caches' }}
              ${{ github.event_name == 'schedule' && '' || 'deleteCaches.push(c)' }}
            }
            
            // delete 
            for (const c of deleteCaches) {
              await github.rest.actions.deleteActionsCacheById({
                owner: owner,
                repo: repo,
                cache_id: c.id,
              })
              console.log(`cleaned cache "${c.key}"`)
            }
