name: pack

permissions:
  contents: write
  actions: read
  id-token: write

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      huggingface_model:
        description: "HuggingFace Model"
        required: true
        type: string
        default: ""
      model_repository:
        description: "Model Repository"
        required: true
        type: string
        default: "thxcode"
      model_name:
        description: "Model Name"
        required: true
        type: string
        default: ""
      model_tag:
        description: "Model Tag"
        required: true
        type: string
        default: ""

jobs:
  pack:
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize Space
        # see https://github.com/easimon/maximize-build-space/blob/master/action.yml.
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_PASSWORD }}
      - name: Get Model
        env:
          HF_TOKEN: ${{ secrets.CI_HUGGINGFACE_TOKEN }}
        run: |
          #!/bin/bash
          
          git lfs install
          git clone --depth 1 https://thxCode:${HF_TOKEN}@huggingface.co/${{ github.event.inputs.huggingface_model }} ${{ github.workspace }}/packs/model
          rm -rf ${{ github.workspace }}/packs/model/.git
      - name: F16
        uses: docker/build-push-action@v6
        with:
          push: true
          target: f16
          file: "${{ github.workspace }}/packs/Dockerfile.${{ github.event.inputs.model_name }}"
          context: ${{ github.workspace }}/packs
          tags: |
            "${{ github.event.inputs.model_repository }}/${{ github.event.inputs.model_name }}:${{ github.event.inputs.model_tag }}-f16"
      - name: Q5_K_M
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "${{ github.workspace }}/packs/Dockerfile.${{ github.event.inputs.model_name }}"
          context: ${{ github.workspace }}/packs
          tags: |
            "${{ github.event.inputs.model_repository }}/${{ github.event.inputs.model_name }}:${{ github.event.inputs.model_tag }}-q5-k-m"
            "${{ github.event.inputs.model_repository }}/${{ github.event.inputs.model_name }}:${{ github.event.inputs.model_tag }}"
      - name: Q6_K
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "${{ github.workspace }}/packs/Dockerfile.${{ github.event.inputs.model_name }}"
          context: ${{ github.workspace }}/packs
          build-args: |
            QUANTIZE_TYPE=Q6_K
          tags: |
            "${{ github.event.inputs.model_repository }}/${{ github.event.inputs.model_name }}:${{ github.event.inputs.model_tag }}-q6-k"
