name: sync

permissions:
  contents: read
  pull-requests: read
  actions: read

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      max-releases:
        description: "Maximum number of releases to sync"
        required: false
        default: 1
        type: number
      dry-run:
        description: "Skip the actual sync"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 */12 * * *" # every 12 hours

jobs:
  gitcode:
    runs-on: ubuntu-22.04
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Sync
        uses: gpustack/.github/actions/mirror-release-gitcode@main
        with:
          gitcode-username: "${{ secrets.CI_GITCODE_USERNAME }}"
          gitcode-password: "${{ secrets.CI_GITCODE_PASSWORD }}"
          gitcode-token: "${{ secrets.CI_GITCODE_TOKEN }}"
          max-releases: "${{ inputs.max-releases && inputs.max-releases || '1' }}"
          dry-run: "${{ inputs.dry-run && inputs.dry-run || 'false' }}"

  gitee:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Sync
        uses: gpustack/.github/actions/mirror-release-gitee@main
        with:
          gitee-username: "${{ secrets.CI_GITEE_USERNAME }}"
          gitee-token: "${{ secrets.CI_GITEE_TOKEN }}"
          max-releases: "${{ inputs.max-releases && inputs.max-releases || '1' }}"
          dry-run: "${{ inputs.dry-run && inputs.dry-run || 'false' }}"

  tencent-cos:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Sync
        env:
          TENCENTCOS_REGION: "ap-guangzhou"
          TENCENTCOS_BUCKET: "gpustack-1303613262"
      - name: Sync
        uses: gpustack/.github/actions/mirror-release-tencent-cos@main
        with:
          tencent-secret-id: "${{ secrets.CI_TECENTCOS_SECRET_ID }}"
          tencent-secret-key: "${{ secrets.CI_TECENTCOS_SECRET_KEY }}"
          tencent-cos-region: "ap-guangzhou"
          tencent-cos-bucket: "gpustack-1303613262"
          max-releases: "${{ inputs.max-releases && inputs.max-releases || '1' }}"
          dry-run: "${{ inputs.dry-run && inputs.dry-run || 'false' }}"
